### ISSUE TITLE
Commits to master get pushed to pantheon prior to completing tests

### ISSUE THREAD

**Issue by aaronbauman** [pantheon-systems/docker-build-tools-ci#45]
Scenario:
- push to master
- build the site
- tests fail

Expected behavior:
- nothing gets pushed to pantheon

Observed behavior:
- changes get pushed through to pantheon even though failing tests should block the push

I believe this is a regression between 4.x (or maybe 5.x) to 6.x.
Will investigate and post a PR.

**Comment by aaronbauman** [comment]
This is a multi-project issue between the docker image set-environment script (this repo) and the example-drops project.

Specifically, the default behavior was changed around the time of this commit: 
https://github.com/pantheon-systems/example-drops-8-composer/pull/255

Specifically, DEFAULT_ENV was changed from `ci-$CIRCLE_BUILD_NUM` to `dev` and "prepare site under test" routine was changed from:
```
terminus -n build:env:create "$TERMINUS_SITE.dev" "$TERMINUS_ENV" --yes --clone-content --notify="$NOTIFY"
```
to 
```
if [[ $CI_BRANCH != $DEFAULT_BRANCH ]]
then
  # Create a new multidev environment (or push to an existing one)
  terminus -n build:env:create "$TERMINUS_SITE.dev" "$TERMINUS_ENV" --yes
else
  # Push to the dev environment
  terminus -n build:env:push "$TERMINUS_SITE.dev" --yes
fi
```

And "merge master" was removed altogether.

From my reading of annotations, I don't see that this was an intentional change, but maybe I'm missing something?

**Comment by greg-1-anderson** [comment]
I believe @ataylorme advocated for and made this change.

**Comment by greg-1-anderson** [comment]
Maybe documentation updates are required?

Is this causing any problems with your workflow, e.g. with multiple developer flows, etc?  I believe the motivation is that with 5+ min tests, PR merges were very slow.

Note that the master branch of your GitHub repository is updated before tests run.

**Comment by aaronbauman** [comment]
It's not a huge problem for our workflow, but was unexpected when we changed versions.
Is the discussion behind this public on github somewhere?
Just want to get all my team on the same page.

**Comment by ataylorme** [comment]
I advocated for this because:

- The workflow we encourage is to use feature branches and only approved changes get merged to `master`. Nothing should go into `master` that isn't ready for `dev`
- As Greg said, creating a `ci-` multidev, and running tests again on merge to `master` is slow
- If the tests pass on the multidev for the pull request, and the PR branch is kept up-to-date with `master`, there should be no change in test results when it is merged
- `dev` is not production and there is no full CD. If tests do fail after `master` is deployed to `dev` the commit to `master` can be reverted
- Our example repos are templates and folks are free to fork/customize them and/or the Dockerfile if they want a different workflow

---

> Maybe documentation updates are required?

I am actively working on rewriting the docs guide and the new version will reflect the current workflow (items merged to `master` get deployed to `dev`).

> It's not a huge problem for our workflow, but was unexpected when we changed versions.

We use semantic versioning on the Dockerfile and this change was made in `5.x` and is documented in the [Dockerfile `README`](https://github.com/pantheon-systems/docker-build-tools-ci#branches)

@aaronbauman where else do you think it should be documented?

> Is the discussion behind this public on github somewhere?

It was discussed in the PR for the change (#23)

**Comment by aaronbauman** [comment]
Thanks for all the background.
This reasoning makes perfect sense to me.

> We use semantic versioning on the Dockerfile and this change was made in 5.x and is documented in the Dockerfile README

I think we went right from 4.x to 6.x, which explains how I missed it (because I definitely always read release notes and READMEs thoroughly ;-)

I'm not sure exactly what else, if anything, should be documented. It has taken me a while to wrap my brain around all the moving parts and how they work together: docker + terminus and plugins + composer example. Maybe a visual would help? i dunno. The [existing guide](https://pantheon.io/docs/guides/build-tools) is very good for getting started, but i didn't really understand how all the tools fit together until i started digging in.

**Comment by ataylorme** [comment]
>  It has taken me a while to wrap my brain around all the moving parts and how they work together: docker + terminus and plugins + composer example. Maybe a visual would help?

Thanks for the feedback. Once I have a version of the updated guide ready for review I'll let you know. There are a lot of moving parts and it is quite complex. 

I'm thinking in addition to the getting started steps in the current guide expanding it to have an advanced section that describes the CI steps/scripts in more detail and explains how the Dockerfile fits in.

**Comment by ataylorme** [comment]
> Once I have a version of the updated guide ready for review I'll let you know.

@aaronbauman you can view a preview of the in-progress guide update [here](https://5151build-static-docs.pantheonsite.io/docs/guides/build-tools)

So far, only the first two sections (introduction and create project) have been updated.

If you have any feedback on those, I'd love to hear it. Feel free to post comments to the [docs pull request](https://github.com/pantheon-systems/documentation/pull/5194).

Our docs were recently converted to Gatsby, so I am working on adding some interactivity to the guide with React. You can see it a bit at the end of the intro (selecting a Git Provider and CI Provider) but it really shines in the create project section, which now has an interactive `build:project:create` command generator.

**Comment by kporras07** [comment]
Reading at this issue history I think it can be closed now. Please reopen or create a new one for further discussion if needed.
